# Generated by Django 3.0.6 on 2020-06-02 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0007_auto_20200529_0957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registrationfm',
        ),
    ]
